name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  test-and-build:
    uses: ./.github/workflows/reusable_test_and_build.yml
    with:
      upload-pages-artifact: true

  deploy:
    needs: test-and-build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
